import React,{useEffect,useRef,useState} from "react";
import {AlertTriangle,Bot,CheckCircle2,Database,Droplets,MessageSquarePlus,Send,ShieldCheck,Sparkles,Thermometer,X} from "lucide-react";
import {api} from "../api";

const assistantWelcome={role:"assistant",content:"Operations Copilot is online. Ask a question or run a guided evidence workflow below."};
function AnimatedCopilotBot(){return <span className="copilot-bot" aria-hidden="true"><i className="bot-orbit outer"/><i className="bot-orbit inner"/><Bot/><i className="bot-signal"/></span>}

export function AgentAssistant(){
 const [open,setOpen]=useState(false),[text,setText]=useState(""),[busy,setBusy]=useState(false),[conversation,setConversation]=useState(null),[activePrompt,setActivePrompt]=useState("");
 const [messages,setMessages]=useState([assistantWelcome]),messagePanel=useRef(null);
 const prompts=[{label:"What needs attention?",query:"What needs attention right now? Give me the incident priorities and evidence."},{label:"Explain climate control",query:"Explain active climate control, current readings and threshold policy."},{label:"Forecast room conditions",query:"Forecast room conditions and identify any predicted threshold breach."},{label:"Latest recovery workflow",query:"Show the latest recovery action, its execution stages and verification result."}];
 useEffect(()=>{const node=messagePanel.current;if(node)node.scrollTo({top:node.scrollHeight,behavior:"smooth"})},[messages,busy]);
 function navigate(page){window.dispatchEvent(new CustomEvent("vtab:navigate",{detail:page}));setOpen(false)}
 function startNewChat(){if(busy)return;setConversation(null);setText("");setActivePrompt("");setMessages([{...assistantWelcome,content:"A new operations workflow is ready. What would you like me to investigate?"}])}
 async function ask(q=text){const question=q.trim();if(!question||busy)return;setText("");setMessages(m=>[...m,{role:"user",content:question}]);setBusy(true);try{const r=await api("/agent/chat",{method:"POST",body:JSON.stringify({message:question,conversation_id:conversation})});setConversation(r.conversation_id);setMessages(m=>[...m,{role:"assistant",content:r.message,evidence:r.evidence,actions:r.suggested_actions,confidence:r.confidence}])}catch(e){setMessages(m=>[...m,{role:"assistant",content:"Live evidence is temporarily unavailable. "+e.message,error:true}])}finally{setBusy(false);setActivePrompt("")}}
 function runPrompt(prompt){if(busy)return;setActivePrompt(prompt.label);ask(prompt.query)}
 return <><button className={`assistant-orb ${open?"open":""}`} onClick={()=>setOpen(v=>!v)} aria-label={open?"Close Operations Copilot":"Open Operations Copilot"} aria-expanded={open}><span className="orb-aura"/><AnimatedCopilotBot/></button>{open&&<section className="assistant-drawer"><header><div className="assistant-title"><small>LIVE OPERATIONS COPILOT</small><h3>Evidence-to-action assistant</h3><span><i/> Connected to telemetry, incidents, forecasts and recovery runs</span></div><div className="assistant-header-actions"><button className="new-chat" onClick={startNewChat} disabled={busy} title="Start a new chat"><MessageSquarePlus/><span>New chat</span></button><button className="close-chat" onClick={()=>setOpen(false)} aria-label="Close copilot"><X/></button></div></header><div className="assistant-workflow"><span><i>1</i>Ask</span><b>→</b><span><i>2</i>Verify evidence</span><b>→</b><span><i>3</i>Open workflow</span></div><div className="assistant-context"><span><i/> LIVE DATABASE</span><span>READ-ONLY EVIDENCE</span><span>AUDITABLE ANSWERS</span></div><div className="assistant-messages" ref={messagePanel} aria-live="polite">{messages.map((m,i)=><article className={`${m.role} ${m.error?"error":""}`} key={i}><b>{m.role==="assistant"?"Operations Copilot":"You"}</b><p>{m.content}</p>{m.evidence?.length>0&&<div className="message-evidence">{m.evidence.map((e,n)=><span key={n}><Database/> {e.label}</span>)}</div>}{m.actions?.length>0&&<div className="message-actions">{m.actions.map((action,n)=><button key={n} onClick={()=>navigate(action.page)}>{action.label}</button>)}</div>}{m.confidence&&<small className="confidence">Evidence confidence {Math.round(m.confidence*100)}%</small>}</article>)}{busy&&<div className="assistant-reading"><Sparkles/><span><b>Correlating live evidence</b><small>{activePrompt||"Checking telemetry, incidents and model runs…"}</small></span></div>}</div><div className="assistant-prompts">{prompts.map(prompt=><button className={activePrompt===prompt.label?"active":""} disabled={busy} key={prompt.label} onClick={()=>runPrompt(prompt)}>{activePrompt===prompt.label?<><Sparkles/> Working…</>:prompt.label}</button>)}</div><form onSubmit={e=>{e.preventDefault();ask()}}><input value={text} onChange={e=>setText(e.target.value)} placeholder="Ask the Operations Copilot…"/><button disabled={busy||!text.trim()} aria-label="Send question"><Send/></button></form></section>}</>
}function ruleTriggered(rule,value){if(value==null||!rule?.enabled)return false;const v=Number(value),t=Number(rule.effective_threshold??rule.threshold);return rule.operator==="gt"?v>t:rule.operator==="gte"?v>=t:rule.operator==="lt"?v<t:rule.operator==="lte"?v<=t:v===t}
function safetyMargin(rule,value,unit){if(value==null||!rule)return "Waiting for reading";const v=Number(value),t=Number(rule.effective_threshold??rule.threshold),distance=Math.abs(t-v).toFixed(1);return ruleTriggered(rule,v)?`${distance}${unit} beyond active limit`:`${distance}${unit} before active limit`}
function temperatureTriggered(rule,value){if(value==null||!rule?.enabled)return false;const v=Number(value),low=Number(rule.effective_lower_threshold??18),high=Number(rule.effective_threshold??rule.threshold??30);return v<low||v>high}
function temperatureMargin(rule,value){if(value==null||!rule)return "Waiting for reading";const v=Number(value),low=Number(rule.effective_lower_threshold??18),high=Number(rule.effective_threshold??rule.threshold??30);if(v<low)return `${(low-v).toFixed(1)}°C below safe band`;if(v>high)return `${(v-high).toFixed(1)}°C above safe band`;return `${Math.min(v-low,high-v).toFixed(1)}°C to nearest boundary`}
export function ClimateStatus(){
 const [data,setData]=useState(null),[rules,setRules]=useState([]);
 useEffect(()=>{const load=()=>Promise.all([api("/agent/climate-control"),api("/settings/thresholds")]).then(([climate,thresholds])=>{setData(climate);setRules(thresholds)}).catch(()=>{});load();const t=setInterval(load,4000);return()=>clearInterval(t)},[]);
 const temperature=rules.find(r=>r.measurement_type==="temperature"),humidity=rules.find(r=>r.measurement_type==="humidity"),tempValue=data?.current?.temperature,humidityValue=data?.current?.humidity,tempRisk=temperatureTriggered(temperature,tempValue),humidityRisk=ruleTriggered(humidity,humidityValue),safe=!tempRisk&&!humidityRisk;
 return <section className={`climate-control useful ${safe?"safe":"attention"}`}><div className="climate-summary">{safe?<CheckCircle2/>:<AlertTriangle/>}<div><small>ENVIRONMENTAL SAFETY</small><h3>{safe?"Climate is within active limits":"Climate requires attention"}</h3><p>{safe?"Current readings are compared with the exact Manual or Auto limits saved in Settings.":"At least one live reading has crossed its active limit. Alert and recovery workflows are monitoring it."}</p></div></div><div className="climate-values"><article className={tempRisk?"risk":""}><Thermometer/><span><small>TEMPERATURE · {temperature?.mode==="auto"?"AUTO":"MANUAL"}</small><b>{tempValue??"—"}°C</b><em>Safe band {temperature?.effective_lower_threshold??18}–{temperature?.effective_threshold??temperature?.threshold??30}°C</em><strong>{temperatureMargin(temperature,tempValue)}</strong></span></article><article className={humidityRisk?"risk":""}><Droplets/><span><small>HUMIDITY · {humidity?.mode==="auto"?"AUTO":"MANUAL"}</small><b>{humidityValue??"—"}%</b><em>Active limit {humidity?.effective_threshold??humidity?.threshold??70}% RH</em><strong>{safetyMargin(humidity,humidityValue,"%")}</strong></span></article></div><footer>Change operating modes and limits in Settings · refreshed every 4 seconds</footer></section>
}
export function IntelligenceGovernance(){
 const [intel,setIntel]=useState([]),[actions,setActions]=useState([]),[error,setError]=useState("");
 useEffect(()=>{const load=()=>Promise.all([api("/agent/intelligence"),api("/agent/actions")]).then(([i,a])=>{setIntel(i);setActions(a);setError("")}).catch(e=>setError(e.message));load();const t=setInterval(load,5000);return()=>clearInterval(t)},[]);
 return <section className="intelligence-governance">
  <div className="live-intelligence"><header><Sparkles/><div><h3>Live predictive intelligence</h3><p>Forecasts and anomaly scores use the active Manual or Auto threshold policy.</p></div><span>REFRESH · 5 SEC</span></header>{error?<aside className="intel-error">Unable to read intelligence: {error}</aside>:<div>{intel.map(x=><article className={x.forecast_breach?"breach":""} key={x.measurement_type}><b>{x.measurement_type.replaceAll("_"," ")}</b><span>Current<strong>{x.current_value}</strong></span><span>Forecast<strong>{x.forecast_value}</strong></span><span>Active limit<strong>{x.threshold??"—"}</strong></span><em>{x.forecast_breach?"EARLY WARNING":x.status.toUpperCase()}</em><small>{x.sample_count} samples · trust {x.trust_score}%</small><details><summary>Model and policy evidence</summary><p>Mode {x.threshold_mode||"manual"} · baseline {x.baseline??(x.threshold_mode==="auto"?"learning":"not used")} · configured base {x.configured_threshold??"—"} · safety ceiling {x.hard_safety_ceiling??"not applicable"} · anomaly score {x.anomaly_score}</p></details></article>)}{!intel.length&&<aside className="intel-empty"><Sparkles/><b>Learning from live telemetry</b><span>Predictions appear after the first validated sensor readings arrive.</span></aside>}</div>}</div>
  <div className="governance-live"><header><ShieldCheck/><div><h3>Governed action lifecycle</h3><p>Auditable AI control and recovery actions, not static status text.</p></div><span>{actions.length} RECORDED</span></header><div>{actions.slice(0,6).map(a=><article key={a.id}><div><b>{a.action_type.replaceAll("_"," ")}</b><em>{a.risk_level} · {a.status.replaceAll("_"," ")}</em></div><p>{a.rationale}</p><ol>{a.timeline.map((step,i)=><li key={i}><i>{step.step}</i>{step.state.replaceAll("_"," ")}</li>)}</ol></article>)}{!actions.length&&<aside><Bot/><b>No automated action is currently required</b><span>When climate control or software recovery runs, each step and verification result appears here.</span></aside>}</div></div>
 </section>
}


