import React,{useEffect,useState} from "react";
import {Activity,Bot,BrainCircuit,CheckCircle2,Database,Network,Send,ShieldCheck,Sparkles} from "lucide-react";
import {api} from "../api";
export default function AgentCenter(){
 const [overview,setOverview]=useState(null),[intel,setIntel]=useState([]),[twin,setTwin]=useState(null),[actions,setActions]=useState([]),[messages,setMessages]=useState([{role:"assistant",content:"I am monitoring the live operations database. Ask about system health, active incidents, or any sensor."}]),[text,setText]=useState(""),[conversation,setConversation]=useState(null),[busy,setBusy]=useState(false),[tab,setTab]=useState("copilot");
 async function load(){try{const [o,i,t,a]=await Promise.all([api("/agent/overview"),api("/agent/intelligence"),api("/agent/digital-twin"),api("/agent/actions")]);setOverview(o);setIntel(i);setTwin(t);setActions(a)}catch(e){console.error(e)}}
 useEffect(()=>{load();const timer=setInterval(load,10000);return()=>clearInterval(timer)},[]);
 async function ask(message=text){if(!message.trim()||busy)return;setText("");setMessages(m=>[...m,{role:"user",content:message}]);setBusy(true);try{const r=await api("/agent/chat",{method:"POST",body:JSON.stringify({message,conversation_id:conversation})});setConversation(r.conversation_id);setMessages(m=>[...m,{role:"assistant",content:r.message,evidence:r.evidence,confidence:r.confidence}])}catch(e){setMessages(m=>[...m,{role:"assistant",content:`Unable to query operations evidence: ${e.message}`,error:true}])}finally{setBusy(false)}}
 async function decide(id,decision){await api(`/agent/actions/${id}/${decision}`,{method:"POST"});load()}
 const snap=overview?.snapshot||{};return <div className="agent-v2">
  <section className="agent-hero"><div className="agent-mark"><Bot/></div><div><small>VTAB SENTINEL 2.0</small><h2>Autonomous Operations Command</h2><p>Sense. Reason. Resolve. Every answer and action remains linked to live evidence.</p></div><span className="agent-live"><i/> AGENT MONITORING</span></section>
  <section className="agent-kpis"><article><Database/><span><b>{snap.devices??"—"}</b> devices</span></article><article><Activity/><span><b>{snap.open_alerts??"—"}</b> active alerts</span></article><article><ShieldCheck/><span><b>{snap.open_incidents??"—"}</b> open tickets</span></article><article><BrainCircuit/><span><b>{intel.length}</b> sensor models</span></article></section>
  <div className="agent-tabs">{[["copilot","AI Manager"],["intelligence","Predictive Intelligence"],["actions","Governed Actions"],["twin","Digital Twin"]].map(([id,label])=><button className={tab===id?"active":""} onClick={()=>setTab(id)} key={id}>{label}</button>)}</div>
  {tab==="copilot"&&<section className="copilot-grid"><div className="agent-chat"><div className="chat-title"><Sparkles/><div><b>Operations Copilot</b><small>Answers from current database evidence</small></div></div><div className="chat-messages">{messages.map((m,n)=><div className={`chat-message ${m.role} ${m.error?"error":""}`} key={n}><b>{m.role==="assistant"?"VTAB Agent":"Manager"}</b><p>{m.content}</p>{m.evidence?.length>0&&<div className="evidence-row">{m.evidence.map((e,i)=><span key={i}><Database/> {e.label}</span>)}</div>}</div>)}{busy&&<div className="agent-thinking"><i/><i/><i/> Reading live evidence</div>}</div><div className="quick-prompts">{["Is the server room healthy?","Show the latest temperature","Are there open incidents?"].map(q=><button onClick={()=>ask(q)} key={q}>{q}</button>)}</div><form onSubmit={e=>{e.preventDefault();ask()}}><input value={text} onChange={e=>setText(e.target.value)} placeholder="Ask the operations manager…"/><button disabled={busy}><Send/></button></form></div><aside className="agent-policy"><ShieldCheck/><h3>Governance policy</h3><div><b>L1 · Automatic</b><span>Safe diagnostics and verified internal recovery.</span></div><div><b>L2 · Approval</b><span>Service changes wait for an authorized manager.</span></div><div><b>L3 · Human led</b><span>Hardware, safety, and destructive actions never run unattended.</span></div><small>All lifecycle steps are auditable and reversible by design.</small></aside></section>}
  {tab==="intelligence"&&<section className="intel-grid">{intel.length?intel.map(x=><article className={`intel-card ${x.status}`} key={x.measurement_type}><header><Activity/><b>{x.measurement_type.replaceAll("_"," ")}</b><em>{x.status}</em></header><div><span>Now<strong>{x.current_value}</strong></span><span>Forecast<strong>{x.forecast_value}</strong></span></div><label>Sensor trust <b>{x.trust_score}%</b><i><u style={{width:`${x.trust_score}%`}}/></i></label><footer>{x.sample_count} samples · anomaly score {x.anomaly_score} · trend {x.trend_per_sample}</footer></article>):<div className="agent-empty">Prediction models are waiting for telemetry samples.</div>}</section>}
  {tab==="actions"&&<section className="agent-actions">{actions.length?actions.map(a=><article key={a.id}><header><ShieldCheck/><b>{a.action_type.replaceAll("_"," ")}</b><em>{a.risk_level} · {a.status.replaceAll("_"," ")}</em></header><p>{a.rationale||"Governed remediation action"}</p><ol>{a.timeline.map((s,i)=><li key={i}><CheckCircle2/><span>Step {s.step}: {s.state.replaceAll("_"," ")}</span></li>)}</ol>{a.status==="awaiting_approval"&&<div><button onClick={()=>decide(a.id,"approve")}>Approve</button><button className="reject" onClick={()=>decide(a.id,"reject")}>Reject</button></div>}</article>):<div className="agent-empty">No remediation actions have been proposed. The agent is monitoring continuously.</div>}</section>}
  {tab==="twin"&&<section className="twin-view">{twin?.sites?.map(site=><article key={site.id}><header><Network/><div><b>{site.name}</b><small>{site.location}</small></div></header>{site.rooms.map(room=><div className="twin-room" key={room.id}><h3>{room.name}</h3>{room.devices.map(d=><div className="twin-device" key={d.id}><span><Database/><b>{d.name}</b><small>{d.hardware_type} · {d.last_seen_at?"telemetry registered":"simulation fallback"}</small></span><div>{d.sensors.map(s=><em key={s.id}>{s.type.replaceAll("_"," ")}</em>)}</div></div>)}</div>)}</article>)}</section>}
 </div>}
