/** Focused AI observability workspace: system health, predictions, model flow and execution evidence. */
import React,{useEffect,useMemo,useState} from "react";
import {Activity,Bot,CheckCircle2,ChevronDown,Database,Filter,LayoutGrid,PauseCircle,Play,Radio,ServerCog,Telescope,XCircle} from "lucide-react";
import {api} from "../api";
import {useVoice} from "../voice/VoiceProvider";
import {IntelligenceGovernance} from "./AgentAssistant";

const stageOrder=["baseline","anomaly","forecast","risk","explanation"],labels={baseline:"Adaptive baseline",anomaly:"Anomaly detector",forecast:"Trend forecast",risk:"Risk engine",explanation:"Explanation engine"};
export default function AITerminal(){
 const [status,setStatus]=useState(null),[diagnostics,setDiagnostics]=useState(null),[evidence,setEvidence]=useState([]),[error,setError]=useState(""),[testing,setTesting]=useState(false),[filter,setFilter]=useState("all"),[lastUpdate,setLastUpdate]=useState(null),[view,setView]=useState("overview");
 const {announce}=useVoice();
 async function refresh(){try{const [data,system,runs]=await Promise.all([api("/ai/status"),api("/system/diagnostics"),api("/ai/results?limit=20")]);setStatus(data);setDiagnostics(system);setEvidence(runs);setLastUpdate(new Date());setError("")}catch(e){setError(`Operations diagnostics unavailable: ${e.message}`)}}
 async function test(){setTesting(true);try{const r=await api("/ai/self-test",{method:"POST"});announce(`AI diagnostic complete. All five models passed. Risk engine returned ${r.result.risk.level} risk.`,{id:`test-${r.result.run_id}`});await refresh()}catch(e){setError(e.message);announce("AI diagnostic failed. Review the operations terminal.",{priority:"critical"})}finally{setTesting(false)}}
 useEffect(()=>{refresh();const timer=setInterval(refresh,2500);return()=>clearInterval(timer)},[]);
 const logs=useMemo(()=>status?.logs?.filter(x=>filter==="all"||x.level===filter)||[],[status,filter]),runs=useMemo(()=>{const ids=[];(status?.logs||[]).forEach(l=>{if(l.run_id&&!ids.includes(l.run_id))ids.push(l.run_id)});return ids.slice(0,8)},[status]);
 const tabs=[["overview","System health",LayoutGrid],["intelligence","Predictive intelligence",Bot],["evidence","Execution evidence",Telescope]];
 return <div className="ai-workspace"><section className="ops-hero"><div className="ops-identity"><div className="pulse-orb"><Bot/></div><div><span className="eyebrow">LIVE MODEL OBSERVABILITY</span><h2>AI Operations Command Center</h2><p>Readable execution evidence from sensor intake through model decision and precaution policy.</p></div></div><div className="ops-actions"><div className={`live-pill ${error?"down":""}`}><Radio/>{error?"CONNECTION LOST":"LIVE MONITORING"}<small>{lastUpdate?`Updated ${lastUpdate.toLocaleTimeString()}`:"Connecting"}</small></div><button className="primary" onClick={test} disabled={testing}><Play/>{testing?"Executing diagnostics…":"Run full diagnostic"}</button></div></section>
  {error&&<div className="terminal-error"><XCircle/>{error}<button onClick={refresh}>Retry</button></div>}
  <Pipeline status={status}/>
  <nav className="ai-section-tabs" aria-label="AI operations sections">{tabs.map(([name,label,Icon])=><button className={view===name?"active":""} onClick={()=>setView(name)} key={name}><Icon/><span><b>{label}</b><small>{name==="overview"?"Services and runtime":name==="intelligence"?"Forecasts and governed actions":"Runs, logs and model data"}</small></span></button>)}</nav>
  {view==="overview"&&<><section className="runtime-strip"><Metric label="Runtime" value={status?.status||"connecting"}/><Metric label="Version" value={status?.version||"—"}/><Metric label="Operational nodes" value={`${status?.models?.filter(m=>["healthy","ready"].includes(m.status)).length||0}/${status?.models?.length||5}`}/><Metric label="Tracked runs" value={runs.length}/><Metric label="Last synchronized" value={lastUpdate?.toLocaleTimeString()||"—"}/></section><section className="diagnostic-panel"><div className="section-heading"><div><ServerCog/><div><h3>Platform dependency diagnostics</h3><p>Live connectivity checks with latency and error evidence</p></div></div><span className={diagnostics?.status||"checking"}>{diagnostics?.status||"checking"}</span></div><div className="component-health">{diagnostics?.components?.map(component=><div className={component.status} key={component.name}>{component.status==="healthy"?<CheckCircle2/>:<XCircle/>}<span><b>{component.name}</b><small>{component.latency_ms} ms</small><em>{typeof component.detail==="string"?component.detail:JSON.stringify(component.detail)}</em></span></div>)||<div className="empty-state">Running dependency checks...</div>}</div><div className="evidence-strip"><div><Database/><span><small>Persisted AI analyses</small><b>{diagnostics?.evidence?.ai_analyses||0}</b></span></div><div><Activity/><span><small>AI-linked alerts</small><b>{diagnostics?.evidence?.ai_linked_alerts||0}</b></span></div><div className={diagnostics?.evidence?.ai_processing_backlog?"error":""}><XCircle/><span><small>AI processing backlog</small><b>{diagnostics?.evidence?.ai_processing_backlog||0}</b></span></div></div></section></>}
  {view==="intelligence"&&<IntelligenceGovernance/>}
  {view==="evidence"&&<div className="terminal-columns focused"><section className="run-ledger"><div className="section-heading"><div><Telescope/><div><h3>Persisted analysis evidence</h3><p>Database-linked AI runs and originating events</p></div></div></div>{evidence.length?evidence.map(run=><button key={run.id} className="run-row"><div className="run-icon"><Activity/></div><div><b>AI {run.id.slice(0,8)}</b><span>Event {run.core_event_id.slice(0,8)} · {new Date(run.analysis_timestamp).toLocaleTimeString()}</span></div><em className={run.risk?.level||run.status}>{run.risk?.level||run.status}</em><ChevronDown/></button>):<div className="empty-state">No persisted AI analysis yet. Publish a scenario from the external Test Lab.</div>}</section><section className="event-console"><div className="console-toolbar"><div><span className="status-dot"/><b>Structured event stream</b></div><div className="log-filters"><Filter/>{["all","info","warning","error"].map(x=><button className={filter===x?"active":""} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div></div><div className="console-scroll">{logs.length?logs.map(log=><div className={`event-line ${log.level}`} key={log.id||log.timestamp+log.message}><time>{new Date(log.timestamp).toLocaleTimeString()}</time><span className="event-level">{log.level}</span><div><b>{log.component} · {log.event||"runtime"}</b><p>{log.message}</p>{Object.keys(log.details||{}).length>0&&<details><summary>Inspect model data</summary><pre>{JSON.stringify(log.details,null,2)}</pre></details>}</div></div>):<div className="empty-state">Waiting for AI runtime events…</div>}</div></section></div>}
 </div>
}
function Pipeline({status}){return <section className="pipeline-map persistent-pipeline"><div className="pipeline-caption"><div><Activity/><span><small>ALWAYS-ON MODEL FLOW</small><b>Five-stage inference pipeline</b></span></div><em>Sensor input → baseline → anomaly → forecast → risk → explanation</em></div><div className="pipeline-nodes">{stageOrder.map((name,index)=>{const model=status?.models?.find(m=>m.name===name),blocked=model?.status==="blocked";return <React.Fragment key={name}><div className={`pipeline-node ${model?.status||"waiting"}`}><div className="node-status">{model?.status==="error"?<XCircle/>:blocked?<PauseCircle/>:<CheckCircle2/>}</div><span>0{index+1} · {blocked?"HELD":model?.status||"waiting"}</span><b>{labels[name]}</b><small>{blocked?`Blocked by ${labels[model.blocked_by]||model.blocked_by}`:`${model?.runs||0} runs · ${model?.latency_ms??"—"} ms`}</small></div>{index<stageOrder.length-1&&<div className={`pipeline-link ${model?.status==="error"||blocked?"stopped":""}`}><i/></div>}</React.Fragment>})}</div></section>}

function Metric({label,value}){return <div><span>{label}</span><strong>{value}</strong></div>}
