import React,{useEffect,useMemo,useState} from "react";
import {AlertOctagon,BellRing,CheckCircle2,ChevronRight,CircuitBoard,Cpu,Fan,Gauge,LockKeyhole,Play,Radio,RotateCcw,Send,ShieldAlert,Siren,TestTubes,TimerReset,Wifi,Zap} from "lucide-react";
import {api} from "../api";
import {useVoice} from "../voice/VoiceProvider";

const DEVICE="00000000-0000-0000-0000-000000000101";
const modules={
 "Nominal operation":{description:"Healthy environmental baseline",values:{temperature:24,humidity:48,water_leak:0,door_open:0,smoke:0}},
 "Cooling degradation":{description:"Rising heat with weak cooling",values:{temperature:36,humidity:54,water_leak:0,door_open:0,smoke:0}},
 "Condensation risk":{description:"High humidity and leak ingress",values:{temperature:27,humidity:86,water_leak:1,door_open:0,smoke:0}},
 "Unauthorized access":{description:"Rack-room door security event",values:{temperature:25,humidity:48,water_leak:0,door_open:1,smoke:0}},
 "Fire emergency":{description:"Smoke and critical heat escalation",values:{temperature:44,humidity:41,water_leak:0,door_open:0,smoke:1}},
 "Compound failure":{description:"Multiple simultaneous sensor hazards",values:{temperature:42,humidity:88,water_leak:1,door_open:1,smoke:1}},
};
const boards={"ESP32 DevKit V1":{chip:"ESP32-WROOM-32",protocol:"Wi-Fi / MQTT",firmware:"sentinel-esp32-2.1"},"Arduino Nano ESP32":{chip:"ESP32-S3",protocol:"Wi-Fi / MQTT",firmware:"sentinel-nano-2.1"}};

export default function TestLab({onSent}){
 const [module,setModule]=useState("Nominal operation"),[board,setBoard]=useState("ESP32 DevKit V1"),[values,setValues]=useState({...modules["Nominal operation"].values}),[auto,setAuto]=useState(false),[sending,setSending]=useState(false),[result,setResult]=useState(null),[timeline,setTimeline]=useState([]);
 const {announce}=useVoice();const boardInfo=boards[board];
 const condition=useMemo(()=>values.smoke?"emergency":values.water_leak||values.temperature>35?"critical":values.humidity>70||values.door_open||values.temperature>30?"warning":"normal",[values]);
 function choose(name){setModule(name);setValues({...modules[name].values});setResult(null);setTimeline([])}
 function update(key,value){setValues(current=>({...current,[key]:value}));setModule("Custom sensor test");setResult(null)}
 async function transmit(){setSending(true);setTimeline([{label:"ESP board transmitted MQTT-compatible payload",state:"done"},{label:"Backend validation and telemetry storage",state:"active"},{label:"Threshold and incident evaluation",state:"waiting"},{label:"AI five-model inference pipeline",state:"waiting"},{label:"Precaution policy generated",state:"waiting"}]);try{
  const ingest=await api("/telemetry/simulate",{method:"POST",body:JSON.stringify({device_id:DEVICE,readings:values,health:{rssi:-42,uptime_seconds:3600,firmware:boardInfo.firmware,board,chip:boardInfo.chip}})});
  setTimeline(x=>x.map((v,i)=>({...v,state:i<3?"done":i===3?"active":"waiting"})));
  const ai=await api("/ai/analyze",{method:"POST",body:JSON.stringify({core_event_id:ingest.core_event_id,telemetry_header_id:ingest.telemetry_header_id,history:{temperature:[23.8,24.1,24,24.2,Number(values.temperature)]},readings:values,horizon:5})});
  setTimeline(x=>x.map(v=>({...v,state:"done"})));setResult({ok:true,ingest,ai,time:new Date()});onSent?.();
  const first=ai.precautions?.[0]?.action||"Review the dashboard";announce(`Incident analysis is complete. ${ai.risk.level} risk, score ${ai.risk.score} out of 100. ${ai.explanation} Recommended action: ${first}`,{priority:["high","critical"].includes(ai.risk.level)?"critical":"normal",id:ai.run_id});
 }catch(error){setTimeline(x=>[...x,{label:`Test failed: ${error.message}`,state:"error"}]);setResult({ok:false,error:error.message,time:new Date()});announce("The system test failed. Review the Test Lab diagnostics.",{priority:"critical"})}finally{setSending(false)}}
 useEffect(()=>{if(!auto)return;const timer=setInterval(transmit,5000);return()=>clearInterval(timer)},[auto,values,board]);
 return <div className="test-lab"><section className="lab-hero"><div><div className="lab-icon"><TestTubes/></div><div><span className="eyebrow">HARDWARE-IN-THE-LOOP SIMULATION</span><h2>VTAB Sensor Test Lab</h2><p>Operate a virtual ESP board, observe every sensor channel, and verify the complete AI response.</p></div></div><div className="lab-controls"><label>Board profile<select value={board} onChange={e=>setBoard(e.target.value)}>{Object.keys(boards).map(x=><option key={x}>{x}</option>)}</select></label><label className="auto-switch"><input type="checkbox" checked={auto} onChange={e=>setAuto(e.target.checked)}/><span/> Continuous test · 5 sec</label></div></section>
  <section className="test-modules"><div className="section-heading"><div><CircuitBoard/><div><h3>Testing modules</h3><p>Select a controlled operating or failure condition</p></div></div><span>{Object.keys(modules).length} validated scenarios</span></div><div className="module-cards">{Object.entries(modules).map(([name,data],i)=><button className={module===name?"selected":""} onClick={()=>choose(name)} key={name}><span>0{i+1}</span><div><b>{name}</b><small>{data.description}</small></div><ChevronRight/></button>)}</div></section>
  <div className="lab-grid"><section className="virtual-rig"><div className="rig-toolbar"><div><Radio/><b>LIVE VIRTUAL RIG</b><span>{boardInfo.protocol}</span></div><div className={`condition ${condition}`}>{condition}</div></div><div className="board-stage"><div className="sensor-bank left"><Sensor icon={<Gauge/>} name="Temperature" value={`${values.temperature} °C`} state={values.temperature>30?"alert":"ok"}/><Sensor icon={<Fan/>} name="Humidity" value={`${values.humidity}% RH`} state={values.humidity>70?"alert":"ok"}/><Sensor icon={<Zap/>} name="Water probe" value={values.water_leak?"WET":"DRY"} state={values.water_leak?"danger":"ok"}/></div><Board name={board} info={boardInfo} condition={condition}/><div className="sensor-bank right"><Sensor icon={<LockKeyhole/>} name="Door contact" value={values.door_open?"OPEN":"SECURE"} state={values.door_open?"alert":"ok"}/><Sensor icon={<Siren/>} name="Smoke sensor" value={values.smoke?"DETECTED":"CLEAR"} state={values.smoke?"danger":"ok"}/><Sensor icon={<Wifi/>} name="Radio link" value="-42 dBm" state="ok"/></div></div><div className="signal-caption"><i/><span>Animated lines indicate active simulated sensor channels feeding the ESP controller</span></div></section>
   <section className="sensor-console"><div className="section-heading"><div><Gauge/><div><h3>Sensor controls</h3><p>Adjust live input values</p></div></div><button className="reset-button" onClick={()=>choose("Nominal operation")}><RotateCcw/> Reset</button></div><Slider name="Temperature" value={values.temperature} min={10} max={55} step={.5} unit="°C" danger={30} onChange={v=>update("temperature",v)}/><Slider name="Humidity" value={values.humidity} min={10} max={100} unit="%" danger={70} onChange={v=>update("humidity",v)}/><Toggle name="Water leak probe" value={values.water_leak} onChange={v=>update("water_leak",v)}/><Toggle name="Door magnetic contact" value={values.door_open} onChange={v=>update("door_open",v)}/><Toggle name="Smoke / fire sensor" value={values.smoke} onChange={v=>update("smoke",v)}/><button className="transmit-button" onClick={transmit} disabled={sending}><Send/>{sending?"Processing through VTAB AI…":"Transmit and analyze now"}</button></section>
  </div>
  <div className="response-grid"><section className="response-timeline"><div className="section-heading"><div><TimerReset/><div><h3>End-to-end processing</h3><p>This is the actual service execution path</p></div></div>{result?.time&&<span>{result.time.toLocaleTimeString()}</span>}</div>{timeline.length?timeline.map((item,i)=><div className={`timeline-item ${item.state}`} key={i}><span>{item.state==="done"?<CheckCircle2/>:item.state==="error"?<AlertOctagon/>:<i/>}</span><div><b>0{i+1}</b><p>{item.label}</p></div></div>):<div className="empty-state">Transmit a test to see every processing stage.</div>}</section><section className={`decision-panel ${result?.ai?.risk?.level||"idle"}`}><div className="decision-head"><div><ShieldAlert/><div><span>AI DECISION</span><h3>{result?.ai?`${result.ai.risk.level} risk` : "Awaiting sensor event"}</h3></div></div>{result?.ai&&<strong>{result.ai.risk.score}<small>/100</small></strong>}</div>{result?.ai?<><p className="explanation">{result.ai.explanation}</p><div className="decision-metrics"><Metric name="Anomaly" value={`${Math.round(result.ai.anomaly.anomaly_score*100)}%`}/><Metric name="Trend" value={result.ai.prediction.trend}/><Metric name="Latency" value={`${result.ai.total_latency_ms} ms`}/></div><h4>Precautionary response</h4><div className="action-list">{result.ai.precautions.map((a,i)=><div key={i}><span className={a.priority}>{i+1}</span><div><b>{a.action}</b><small>{a.automation.replaceAll("_"," ")}</small></div></div>)}</div><button className="open-terminal" onClick={()=>window.dispatchEvent(new CustomEvent("vtab:navigate",{detail:"AI Operations"}))}>Open correlated AI run <ChevronRight/></button></>:<div className="decision-placeholder"><Cpu/><p>AI results, operational precautions, and automated-response status will appear here.</p></div>}</section></div>
 </div>
}
function Board({name,info,condition}){return <div className={`esp-board ${condition}`}><div className="board-pins top">{Array.from({length:12},(_,i)=><i key={i}/>)}</div><div className="board-core"><div className="usb-port"/><Cpu/><span>{info.chip}</span><b>{name}</b><small>{info.firmware}</small><div className="board-leds"><i/><i/><i/></div></div><div className="board-pins bottom">{Array.from({length:12},(_,i)=><i key={i}/>)}</div></div>}
function Sensor({icon,name,value,state}){return <div className={`rig-sensor ${state}`}><span>{icon}</span><div><small>{name}</small><b>{value}</b></div><i/></div>}
function Slider({name,value,min,max,step=1,unit,danger,onChange}){const pct=(value-min)/(max-min)*100;return <div className={`lab-slider ${value>danger?"alert":""}`}><div><label>{name}</label><strong>{value}{unit}</strong></div><input style={{"--value":`${pct}%`}} type="range" min={min} max={max} step={step} value={value} onChange={e=>onChange(Number(e.target.value))}/><div><span>{min}{unit}</span><span>Alert above {danger}{unit}</span><span>{max}{unit}</span></div></div>}
function Toggle({name,value,onChange}){return <button className={`sensor-toggle ${value?"triggered":""}`} onClick={()=>onChange(value?0:1)}><div><i/><span>{name}</span></div><b>{value?"TRIGGERED":"NORMAL"}</b></button>}
function Metric({name,value}){return <div><span>{name}</span><b>{value}</b></div>}
