import React,{useEffect,useMemo,useRef,useState} from "react";
import {Activity,AlertTriangle,CheckCircle2,CircuitBoard,CloudUpload,Cpu,DoorOpen,Droplets,Flame,Gauge,Pause,Play,Radio,RotateCcw,Server,ShieldCheck,Wifi} from "lucide-react";
import {createRoot} from "react-dom/client";
import "./styles.css";

const API=import.meta.env.VITE_SIMULATOR_API_URL||"http://localhost:8010";
const scenarios={
 "Nominal operation":{temperature:24,humidity:48,water_leak:0,door_open:0,smoke:0},
 "Cooling degradation":{temperature:36,humidity:55,water_leak:0,door_open:0,smoke:0},
 "Condensation and leak":{temperature:27,humidity:86,water_leak:1,door_open:0,smoke:0},
 "Unauthorized access":{temperature:25,humidity:48,water_leak:0,door_open:1,smoke:0},
 "Fire emergency":{temperature:44,humidity:41,water_leak:0,door_open:0,smoke:1},
 "Compound failure":{temperature:42,humidity:88,water_leak:1,door_open:1,smoke:1},
};

function App(){
 const [mode,setMode]=useState("hardware"),[scenario,setScenario]=useState("Nominal operation"),[values,setValues]=useState({...scenarios[scenario]}),[status,setStatus]=useState(null),[result,setResult]=useState(null),[sending,setSending]=useState(false),[streaming,setStreaming]=useState(true);const valuesRef=useRef(values),sendingRef=useRef(false);useEffect(()=>{valuesRef.current=values},[values]);
 useEffect(()=>{const check=()=>fetch(`${API}/status`).then(r=>r.json()).then(setStatus).catch(()=>setStatus(null));check();const t=setInterval(check,3000);return()=>clearInterval(t)},[]);
 const condition=useMemo(()=>values.smoke?"emergency":values.water_leak||values.temperature>35?"critical":values.door_open||values.humidity>70||values.temperature>30?"warning":"normal",[values]);const phase=result?.ok?(result.processing?"processing":"complete"):result?"error":streaming?"streaming":"ready";
 function select(name){setScenario(name);setValues({...scenarios[name]});setResult(null)}
 function update(key,value){setScenario("Custom test");setValues(v=>({...v,[key]:value}));setResult(null)}
 async function publish(continuous=false){if(sendingRef.current)return;sendingRef.current=true;setSending(true);if(!continuous)setResult(null);try{const response=await fetch(`${API}/publish`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({readings:valuesRef.current,board:"ESP32 DevKit V1",firmware:"sentinel-esp32-lab-3.0",rssi:-42})});const data=await response.json();if(!response.ok)throw new Error(data.detail||"Publish failed");setResult({ok:true,processing:true,...data});setStatus(s=>s?{...s,last_publish_at:data.timestamp,published:(s.published||0)+1}:s);let receipt=null;for(let attempt=0;attempt<30;attempt++){await new Promise(resolve=>setTimeout(resolve,1000));const r=await fetch(`${API}/receipts/${data.correlation_id}`);receipt=await r.json();if(receipt.status==="complete")break}if(receipt?.status!=="complete")throw new Error("MQTT was acknowledged, but database processing did not confirm within 30 seconds. Check mqtt-worker logs.");setResult({ok:true,processing:false,...data,receipt})}catch(error){setResult({ok:false,error:error.message});setStreaming(false)}finally{sendingRef.current=false;setSending(false)}}
 useEffect(()=>{if(!streaming||mode!=="hardware")return;publish(true);const timer=setInterval(()=>publish(true),8000);return()=>clearInterval(timer)},[streaming,mode]);
 if(mode==="software")return <main><header><div className="brand"><ShieldCheck/><div><span>VTAB SENTINEL</span><h1>Unified System Simulator</h1><p>Hardware telemetry and software reliability testing in one application</p></div></div></header><ModeTabs mode={mode} setMode={setMode}/><iframe className="software-lab-frame" title="Software reliability test console" src="/software/"/></main>;
 return <main><header><div className="brand"><ShieldCheck/><div><span>VTAB SENTINEL</span><h1>Independent ESP32 Test Lab</h1><p>External hardware simulator · isolated from the operational dashboard</p></div></div><div className={`stream-state ${streaming?"online":"paused"}`}><Activity/><span><b>{streaming?"LIVE SENSOR STREAM":"STREAM PAUSED"}</b><small>{streaming?"Automatic packet every 8 seconds":"Manual publishing remains available"}</small></span></div></header>
 <ModeTabs mode={mode} setMode={setMode}/><section className={`route phase-${phase}`}><Stage icon={<Gauge/>} n="01" title="Sensor controls" status="done"/><i/><Stage icon={<Wifi/>} n="02" title="MQTT transport" status={phase==="ready"?"waiting":"active"}/><i/><Stage icon={<Server/>} n="03" title="Database ingestion" status={phase==="complete"?"done":phase==="processing"?"active":"waiting"}/><i/><Stage icon={<Cpu/>} n="04" title="Alerts and AI" status={phase==="complete"?"done":phase==="error"?"error":"waiting"}/></section>
 <section className="scenario-panel"><div><CircuitBoard/><span><b>Test scenarios</b><small>Select a controlled ESP32 input condition</small></span></div><div className="scenarios">{Object.keys(scenarios).map(name=><button className={scenario===name?"active":""} onClick={()=>select(name)} key={name}>{name}</button>)}</div><button className={`stream ${streaming?"active":""}`} onClick={()=>setStreaming(v=>!v)}>{streaming?<Pause/>:<Play/>}<span>{streaming?"Stop live stream":"Start live stream"}<small>{streaming?"Publishing every 8 seconds":"Create a realistic sensor pulse"}</small></span></button></section>
 <div className="workspace"><section className={`rig ${condition}`}><div className="rig-title"><div><Activity/><span><b>LIVE SENSOR RIG</b><small>ESP32-WROOM-32 · Wi-Fi telemetry</small></span></div><em>{condition}</em></div><div className="sensor-grid"><Sensor icon={<Gauge/>} label="Temperature" value={`${values.temperature} °C`} alert={values.temperature>30}/><Sensor icon={<Droplets/>} label="Humidity" value={`${values.humidity}% RH`} alert={values.humidity>70}/><Sensor icon={<Droplets/>} label="Water probe" value={values.water_leak?"WET":"DRY"} alert={values.water_leak}/><Sensor icon={<DoorOpen/>} label="Door contact" value={values.door_open?"OPEN":"SECURE"} alert={values.door_open}/><Sensor icon={<Flame/>} label="Smoke" value={values.smoke?"DETECTED":"CLEAR"} alert={values.smoke}/><Sensor icon={<Wifi/>} label="Signal" value="-42 dBm"/></div><div className="board"><div className="pins"/><Cpu/><b>ESP32-WROOM-32</b><small>sentinel-esp32-lab-3.0</small></div></section>
 <section className="controls"><div className="title"><div><h2>Sensor variables</h2><p>Values are published as one hardware telemetry packet.</p></div><button onClick={()=>select("Nominal operation")}><RotateCcw/> Reset</button></div><Slider label="Temperature" value={values.temperature} min={10} max={55} unit="°C" onChange={v=>update("temperature",v)}/><Slider label="Humidity" value={values.humidity} min={10} max={100} unit="%" onChange={v=>update("humidity",v)}/><Toggle label="Water leak probe" value={values.water_leak} onChange={v=>update("water_leak",v)}/><Toggle label="Door magnetic contact" value={values.door_open} onChange={v=>update("door_open",v)}/><Toggle label="Smoke / fire sensor" value={values.smoke} onChange={v=>update("smoke",v)}/><button className="publish" disabled={sending} onClick={publish}><CloudUpload/>{sending?"Publishing to MQTT...":"Publish ESP32 telemetry"}</button></section></div>
 <section className={`receipt ${result?.ok?"success":result?"error":""}`}><div>{result?.ok?<CheckCircle2/>:<AlertTriangle/>}<span><b>{result?.processing?"MQTT acknowledged - waiting for database and AI":result?.ok?"End-to-end processing confirmed":result?"Transmission failed":"Awaiting a test transmission"}</b><small>{result?.ok?`Correlation ${result.correlation_id} · ${new Date(result.timestamp).toLocaleString()}`:result?.error||"The simulator does not write directly to the database or call AI APIs."}</small></span></div>{result?.ok&&<div className="next"><b>{result.processing?"Processing":"Verified result"}</b><span>{result.processing?"MQTT worker → database → alerts → AI":`Database: ${result.receipt.database} · Tickets created: ${result.receipt.alerts_created} · AI: ${result.receipt.ai_status}`}</span><a href="http://localhost:5173" target="_blank">Open operational dashboard</a></div>}</section>
 </main>}
function ModeTabs({mode,setMode}){return <nav className="simulator-tabs"><button className={mode==="hardware"?"active":""} onClick={()=>setMode("hardware")}><CircuitBoard/> Hardware / ESP32 Lab<span>Sensor telemetry and physical scenarios</span></button><button className={mode==="software"?"active":""} onClick={()=>setMode("software")}><Cpu/> Software / AI Lab<span>Services, named models and failure response</span></button></nav>}
function Stage({icon,n,title,status}){return <div className={`stage ${status}`}>{icon}<span><small>{n} · {status}</small><b>{title}</b></span><em/></div>}
function Sensor({icon,label,value,alert}){return <div className={alert?"alert":""}><span>{icon}</span><small>{label}</small><b>{value}</b><i/></div>}
function Slider({label,value,min,max,unit,onChange}){return <label className="slider"><span><b>{label}</b><strong>{value}{unit}</strong></span><input type="range" min={min} max={max} step={label==="Temperature"?.5:1} value={value} onChange={e=>onChange(Number(e.target.value))}/><small>{min}{unit}<em>Alert threshold monitored by VTAB</em>{max}{unit}</small></label>}
function Toggle({label,value,onChange}){return <button className={`toggle ${value?"triggered":""}`} onClick={()=>onChange(value?0:1)}><span><i/>{label}</span><b>{value?"TRIGGERED":"NORMAL"}</b></button>}
createRoot(document.getElementById("root")).render(<App/>);
