server {
  listen 80;
  root /usr/share/nginx/html;
  index index.html;
  location /software/ { proxy_pass http://software-lab:8011/; proxy_set_header Host $host; }
  location / { try_files $uri /index.html; }
}
